<?xml version="1.0" encoding="utf-8"?><Database Name="ESP" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-69AAMS8P\SQLEXPRESS;Initial Catalog=ESP;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="WindowsFormsApp2.Properties.Settings" SettingsPropertyName="ESPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[values]" Member="values">
    <Type Name="value">
      <Column Name="ID" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Temp" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Hum" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>